# Generated by Django 5.2.6 on 2026-09-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(choices=[('Raw_materials', 'raw_materials'), ('Finished_goods', 'finished_goods'), ('Packing_materials', 'packing_materials'), ('Consumable', 'consumable')], max_length=100)),
                ('unit_of_measure', models.CharField(choices=[('KG', 'Kilogram'), ('L', 'Liter'), ('PCS', 'Pieces'), ('BOX', 'Boxes'), ('CTN', 'Cartons'), ('PACK', 'Packs')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('reorder_level', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_category', to='inventory.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
            ],
            options={
                'ordering': ['company', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_company_product_name'), models.UniqueConstraint(fields=('company', 'sku'), name='unique_company_sku_name')],
            },
        ),
    ]
