# Generated by Django 5.2.6 on 2026-09-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='minimum_quatity_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
