# Generated by Django 5.2.6 on 2026-09-14 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=100)),
                ('warehouse_code', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('warehouse_type', models.CharField(choices=[('Raw_materials', 'RAW_MATERIALS'), ('Packing_materials', 'PACKING_MATERIALS'), ('Finished_goods', 'FINISHED_GOODS'), ('Cold_storage', 'COLD_STORAGE'), ('Damaged', 'DAMAGED'), ('Chemical_storage', 'CHEMICAL_STORAGE'), ('Distribution_center', 'DISTRIBUTION_CENTER')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity_unit', models.CharField(blank=True, choices=[('Pallets', 'PALLETS'), ('Carton', 'CARTON'), ('Boxes', 'BOXES'), ('Kilogram', 'KG'), ('Liters', 'LITERS')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'warehouse_name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'warehouse_name'), name='unique_company_warehouse_type'), models.UniqueConstraint(fields=('company', 'warehouse_code'), name='unique_company_warehouse_code')],
            },
        ),
    ]
