# Generated by Django 5.2.6 on 2026-09-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_system_admin',
            field=models.BooleanField(default=False),
        ),
    ]
